blog/urls.py
from django.conf.urls import url, include
from . import views
from .feeds import AllPostsRssFeed

# app_name = 'sites'
urlpatterns = [

    # 主页面
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^test$', views.test, name="test"),
    # 关于页面
    url(r'^about$', views.about, name="about"),
    # 下载 app
    url(r'^app$', views.app),

    # 注册操作
    url(r'^accounts/register/vmobile$', views.register_vmobile),
    url(r'^accounts/register/next$', views.register_next),
    url(r'^accounts/register$', views.register, name="register"),
    # 登录操作
    url(r'^accounts/profile', views.sign_in),

    # 将 auth 应用中的 urls 模块包含进来
    url(r'^users/', include('django.contrib.auth.urls')),
    # publish
    # 发表文章
    url(r'^articles/publish$', views.publish, name="publish"),
    # 文章页面
    url(r'^articles/(?P<pk>\d+)$', views.PostDetailView.as_view(), name="detail"),
    # 修改文章
    url(r'^articles/(?P<pk>\d+)/update$', views.article_update, name="update"),
    # 评论
    url(r'^comments/publish/(?P<pk>\d+)$', views.comment),

    # 评论前的验证
    url(r'^comments/verify$', views.verf_image_code),

    # 返回验证码图片
    url(r'^passports/captcha$', views.captcha_image),


    # 按月归档
    url(r'^archives/(?P<year>\d{4})/(?P<month>\d{1,2})$', views.ArchivesView.as_view(), name="archives"),
    # 分类
    url(r'^categories/(?P<pk>\d+)$', views.CategoryView.as_view(), name="category"),
    # 按标签归档文章
    url(r'^tags/(?P<pk>\d+)$', views.TagView.as_view(), name="tag"),

    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
]

sites/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('blockchain.views')),
    url(r'api/v1/', include('blogapi.api_v1')),
    url(r'', include('webreader.views')),
    url(r'^search/', include('haystack.urls')),
    url(r'', include('oauth2.views')),
]

# if django_settings.DEBUG:
#     urlpatterns.extend([
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#             {"document_root": django_settings.MEDIA_ROOT}),
#         url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#             {"document_root": django_settings.STATIC_ROOT}),
#         url(r"^c.js", 'django.contrib.staticfiles.views.serve',
#             {"path": "adscript/d.js", "insecure": True}),
#     ])

blog/models.py
import markdown
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.html import strip_tags
import django.utils.timezone as timezone
from django.urls import reverse


class Github(models.Model):
    """ Github """
    login_name = models.CharField(max_length=30, verbose_name='Github 登录名')
    github_id = models.IntegerField(verbose_name='Github 用户ID')
    avatar_url = models.URLField(verbose_name='头像', blank=True)

    def __str__(self):
        return "Github<Github:{}>".format(self.login_name)


class User(AbstractUser):
    """ 用户 """
    phone_number = models.CharField(max_length=13, verbose_name="手机号")
    github = models.ForeignKey(Github, verbose_name='与用户关联的 Github', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "用户<用户名:{}>".format(self.username)


class Category(models.Model):
    """ 分类 """
    name = models.CharField(max_length=100, verbose_name="分类名")

    def __str__(self):
        return "分类<分类名:{}>".format(self.name)


class Tag(models.Model):
    """ 标签 """
    name = models.CharField(max_length=100, verbose_name="标签名")

    def __str__(self):
        return "标签<标签名:{}>".format(self.name)


class Post(models.Model):
    """ 文章 """
    title = models.CharField(max_length=70, verbose_name="文章标题")
    body = models.TextField(verbose_name="文章内容")
    # timezone.now 默认为当前时间并且可以修改
    create_time = models.DateTimeField(default=timezone.now, verbose_name="创建时间")
    modify_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")
    abstract = models.CharField(max_length=200, blank=True, verbose_name="文章摘要")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览数量")
    category = models.ForeignKey(Category, verbose_name="分类")
    tags = models.ManyToManyField(Tag, blank=True, verbose_name="标签")
    author = models.ForeignKey(User, verbose_name="作者")

    class Meta:
        ordering = ['-create_time']

    def __str__(self):
        return "文章<标题:{}>".format(self.title)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})
    """
    自动生成文章摘要： 重写 save() 方法， 将 markdown 转为 html 文本， 
    去掉 html 标签， 然后截取前 54 个字符做摘要 
    """
    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        # 实例化一个 markdown
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite'
        ])
        """
        先将 Markdown 文本渲染成 HTML 文本
        strip_tags 去掉 HTML 文本的全部 HTML 标签
        从文本摘取前 54 个字符赋给 excerpt
        """
        self.abstract = strip_tags(md.convert(self.body))[:54]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

comment/models.py
from django.db import models
from blog.models import User, Post


class Comment(models.Model):
    """ 评论 """
    tourist = models.ForeignKey(User, verbose_name="评论人")
    content = models.TextField(verbose_name="评论内容")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    post = models.ForeignKey(Post, verbose_name="评论的文章")

    class Meta:
        ordering = ['-create_time']

    def __str__(self):
        return "评论<评论者:{}>".format(self.content[:20])

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User, Post
from comment.models import Comment


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", )


class PublishForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body', 'tags', "category"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

blog/views.py
import os
import markdown
import re
import logging
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.http import HttpResponse, StreamingHttpResponse
from django.conf import settings
from django.core.mail import send_mail
from .models import Post, Category, Tag, User
from .forms import RegisterForm, CommentForm, PublishForm
from .verf_mobile_code import send_code, generate_verification_code
from .verf_image_code import get_random_code, generate_random_code


logger = logging.getLogger(__name__)


def test(request):
    """ 跳转到关于网站的页面 """
    return render(request, 'test.html')


class IndexView(ListView):
    """ 首页 """
    model = Post
    template_name = 'index.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        if not user.is_authenticated():
            qs = Post.objects.filter(author__username='Misaka')
        else:
            qs = Post.objects.filter(author=user)
        return qs

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


def sign_in(request):
    """ 登录操作 """
    return redirect('/')


def about(request):
    """ 跳转到关于网站的页面 """
    return render(request, 'about.html')


def app(request):
    """ 下载 """
    path = os.path.dirname(__file__)

    def file_iterator(file, chunk_size=1024):
        with open(file) as f:
            while True:
                c = f.read(chunk_size)
                if c:
                    yield
                else:
                    break
    file_name = os.path.join(path, "static/app/" + "app.apk")
    response = StreamingHttpResponse(file_iterator(file_name))
    # 保存到硬盘时不会乱码
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{0}"'.format(file_name)
    return response


def register_vmobile(request):
    """ 注册时发送验证码操作 """
    if request.method == 'GET':
        return HttpResponse("failed")

    phone_number = request.POST.get('phone_number')

    # 清除旧的验证码
    if phone_number in request.session:
        request.session.delete(phone_number)

    """
    activate_code 为 6 位数字随机验证码, send_code_status 为阿里云 SDK 
    生成验证码的状态信息， 为 'OK' 时表示验证码生成成功.
    """
    activate_code = generate_verification_code()
    send_code_status = send_code(activate_code, phone_number)
    if send_code_status != 'OK':
        return HttpResponse("failed")

    # 将验证码存在 session 中， 格式<手机号， 验证码>
    request.session[phone_number] = activate_code
    # 设置会话过期时间
    request.session.set_expiry(10 * 60)
    return HttpResponse("success")


def register_next(request):
    """ 验证手机验证码是否正确 """

    ctx = {}
    if request.method == 'GET':
        return render(request, 'users/register.html')

    ctx['message'] = "手机号有误，请重新验证"
    phone_number = request.POST.get('phone_number')
    vmobile_code = request.POST.get('vmobile_code')

    # 没有填写手机号或验证码已过期
    if phone_number not in request.session:
        render(request, 'users/register.html', ctx)

    ctx['message'] = "验证码输入不正确"
    activate_code = request.session.get(phone_number)

    # 验证码输入不正确
    if vmobile_code != activate_code:
        render(request, 'users/register.html', ctx)

    # 将手机号存在 session 中， 格式<‘phone_number’， 手机号>
    request.session['phone_number'] = phone_number
    request.session.set_expiry(10 * 60)
    ctx['message'] = "验证成功"
    ctx['step'] = 2  # 当前注册进度为 2
    return render(request, 'users/register.html', ctx)


def register(request):

    """ 注册帐号 采用两步认证的方法 """
    if request.method == 'GET':
        return render(request, 'users/register.html')

    # 当前注册进度为 2, 默认进度为 None
    ctx = {'step': 2}

    if request.method == 'POST':
        phone_number = request.session.get('phone_number')
        if phone_number is None:
            ctx['message'] = "会话已过期，请重新验证手机"
            return render(request, 'users/register.html', ctx)
        if not re.findall(r"1[34578]\d{9}", phone_number):
            ctx['message'] = "手机号有误， 请重新验证"
            return render(request, 'users/register.html', ctx)

        form = RegisterForm(request.POST)
        if not form.is_valid():
            ctx['message'] = form.errors
            return render(request, 'users/register.html', ctx)

        # 创建实例，需要做些数据处理，暂不做保存
        new_user = form.save(commit=False)
        new_user.phone_number = phone_number
        new_user.save()
        del request.session['phone_number']
        ctx['message'] = "注册成功"
        ctx['step'] = 3
        return render(request, "users/register.html", ctx)

    return render(request, "users/register.html", ctx)


def publish(request):
    """ 发布文章 """

    """ 写博客的页面 """
    if request.method == 'GET':
        return render(request, "publish.html")

    author = request.user
    # 未登录
    if not author.is_authenticated:
        return render(request, "publish.html", {"err": "未登录"})

    # FIXME: ModelForm 多对多表单验证与多对一验证
    form = PublishForm(request.POST)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = author
        form.save()
        redirect_url = "/articles/" + str(new_post.id)
        return HttpResponseRedirect(redirect_url)
    else:
        return render(request, "publish.html", form.errors)


def article_update(request, pk):
    """ 发布文章 """
    post = get_object_or_404(Post, pk=pk)
    """ 写博客的页面 """
    if request.method == 'GET':
        return render(request, "publish_update.html", {"post": post})

    author = request.user
    # 未登录
    if author != post.author:
        return render(request, "publish_detail.html", {"err": "未登录"})

webreader/views.py
from django.conf.urls import url
from django.shortcuts import render


def web_reader(request):
    return render(request, 'reader.html')


app_name = 'webreader'
urlpatterns = [
    url(r'^webreader/$', web_reader, name='webreader'),
]

blog/templates/article.html
<article class="articles">
    <header class="entry_header">
        <h1 class="entry_title"><a href="/articles/{{ post.id }}" class="title_font">{{ post.title }}</a></h1>
        <div class="entry_meta">
            <span class="post_category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post_date"><a href="#">{{ post.create_time|date:"Y年m月d日 H:m" }}</a></span>
            <span class="post_author"><a href="#">{{ post.author.username }}</a></span>
            <span class="comments_link"><a href="{{ post.get_absolute_url }}">{{post.comment_set.count}} 评论</a></span>
            <span class="views_count"><a href="{{ post.get_absolute_url }}">{{post.views}} 阅读</a></span>
        </div>
    </header>
    <div class="entry_content">{{ post.abstract|safe }}</div>
</article>

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <style>
        body {margin: 0;}
        .header {display: -webkit-flex;display: flex;flex-direction: row;height: 68px;margin: 0 auto;}
        .logo {-webkit-flex: 1; flex: 1;}
        .navbar {-webkit-flex: 1; flex: 1;display: -webkit-flex;display: flex;flex-direction: row;}
        .navbar-1 {-webkit-flex: 1; flex: 1;}
        .navbar-2 {-webkit-flex: 1; flex: 1;}
        .navbar-3 {-webkit-flex: 1; flex: 1;}
        .user-info {-webkit-flex: 1; flex: 1;display: -webkit-flex;display: flex;flex-direction: row;}
        .register {-webkit-flex: 1; flex: 1;}
        .login {-webkit-flex: 1; flex: 1;}
        .logout {-webkit-flex: 1; flex: 1;}
        .content {display: -webkit-flex;display: flex;flex-direction: row;padding-bottom: 20px;}
        @media (min-width: 1024px){.aside-left {-webkit-flex: 1; flex: 1;}}
        .main {-webkit-flex: 2; flex: 2; border: 1px solid #f78a09; margin-right: 20px;}
        .aside-right {-webkit-flex: 1; flex: 1;border: 1px solid #f78a09}
        @media (min-width: 1024px){.blank {-webkit-flex: 1; flex: 1;}}
        .footer {display: -webkit-flex;display: flex;flex-direction: row;-webkit-flex: 1; flex: 1;}
    </style>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-152710976-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-152710976-1');
    </script>
</head>
<body>
    <div class="header">
    <div class="blank"></div>
        <div class="logo"><a href="{% url 'index' %}">WATERLAW</a></div>
        <div class="navbar">
            <div class="navbar-1"><a href="{% url 'index' %}">首页</a></div>
            <div class="navbar-2"><a href="{% url 'publish' %}">写文章</a></div>
            <div class="navbar-3"><a href="{% url 'webreader:webreader' %}">阅读</a></div>
        </div>
        <div class="user-info">
            {% if not user.is_authenticated %}
            <div class="register"><a href="{% url 'register' %}?next={{ request.path }}">注册</a></div>
                <div class="login"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></div>
            {% else %}
                <div class="logout"><span>{{ user.username }} </span><a href="{% url 'logout' %}?next={{ request.path }}">退出</a></div>
            {% endif %}
        </div>
    <div class="blank"></div>
    </div>

    <div class="content">
        <div class="aside-left"></div>
        <div class="main">
            {% block main %}
            {% endblock main %}
        </div>
        <div class="aside-right">
            {% block aside-right %}
            {% endblock aside-right %}
        </div>
        <div class="blank"></div>
    </div>
    {% block pagination %}
    {% endblock pagination %}
    <div class="footer">
        <div class="blank"></div>
        <div class="copyright">@copyright belongs to jianping.zhang.</div>
        <div class="blank"></div>
    </div>
</body>
</html>

blog/templates/publish.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}


{% block title %}
    Write Pager
{% endblock title %}

{% block main %}
    <form action="/articles/publish" method="post">
        {% csrf_token %}
        <div>
            <span>标题</span>
            <span><input name="title"></span>
        </div>
        <hr />
        <div>
            <div>
                <span>分类</span>
                <span>
                            {% get_all_categories as categories %}
                            <select name="category" id="post_category" style="height: 24px;">
                                {% for category in categories %}
                                    <option value="{{ category.id }}"
                                            style="font-size:14px;">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </span>
            </div>
            <hr />
            <div style="display: flex;align-content: baseline;">
                <span style="margin-right: 4px;">标签</span>
                <span>
                            {% get_all_tags as tags %}
                            <select name="tags" id="post_tags" multiple="multiple">
                                {% for tag in tags %}
                                    <option value="{{ tag.id }}" style="font-size:16px;">{{ tag.name }}</option>
                                {% endfor %}
                            </select>
                        </span>
            </div>
        </div>
        <div id="layout">
            <div id="use-editormd">
                <textarea style="width: 733px; max-width: 733px; height: 960px;border: 1px solid black" name="body"></textarea>
            </div>
        </div>
        <button style="float:left;padding:1px 2px;width: 60px;">预览</button>
        <div>
            <div>
                <div>
                    <div style="float:right;padding:1px 2px">
                        <button>发布文章</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}


{% block aside-right %}
    本网站已支持 Github 登录
    {% if not user.is_authenticated %}
        ，<a href="https://www.waterlaw.top/users/login/?next=/">去登录</a>
    {% endif %}
{% endblock aside-right %}

blog/templates/publish_detail.html
{% extends "base.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block main %}
    <div class="container">
        <div class="row">
            <main class="span16">
                <article class="articles">
                    <header class="entry_header">
                        <h1 class="entry_title"><a href="{{ post.get_absolute_url }}"
                                                   class="title_font">{{ post.title }}</a></h1>
                        <div class="entry_meta">
                            <span class="post_category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post_date"><a href="#">{{ post.create_time|date:"Y年m月d日 H:m" }}</a></span>
                            <span class="post_author"><a href="#">{{ post.author.username }}</a></span>
                            <span class="comments_link"><a
                                    href="{{ post.get_absolute_url }}">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views_count"><a
                                    href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                            {% if post.author == user %}
                            <span class="post_update"><a
                                    href="{% url 'update' post.pk %}">修改</a></span>
                            {% endif %}
                        </div>
                    </header>
                    <div class="entry_content">{{ post.body|safe }}</div>
                </article>
                <section class="comment_area">
                    {% comment %}<div class="row">
                        <div class="span12">
                            <span>验证码：</span>
                            <span><input id="send_image_code" name="image_code"></span>
                            <span>
                            <img src="/passports/captcha" alt="passport"
                                 style="width:120px;height:30px" onclick="this.src='/passports/captcha?d='+new Date().getTime()">
                        </span>
                        </div>
                    </div>{% endcomment %}
                    <div class="post_comment">
                        <h3 class="post_comment_title">发表评论</h3>
                        <form action="/comments/publish/{{ post.id }}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <!--
                                <div class="span12 fix">
                                    <span>评论人</span>
                                    <span><input name="name"></span>
                                </div>-->
                                <div class="span14">
                                    <span class="span14">评论内容</span>
                                    <span>
                                    <textarea name="content" class="content" style="width:99%;height: 200px;border: 1px solid black;"></textarea>
                                </span>
                                    <div class="span13">&nbsp;</div>
                                    <span class="post_comment_btn">
                                    <button class="button">发表</button>
                                </span>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="comment_list_panel">
                        <h3>评论列表, 共
                            <span>{{ comment_list.count }}</span> 条评论
                        </h3>
                        <ul>
                            {% for comment in comment_list %}
                                <li>
                                    <span>{{ comment.tourist.username }} 评论于</span>
                                    <time>{{ comment.create_time|date:"Y年m月d日 H:m" }}</time>
                                    <article>{{ comment.content }}</article>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </section>
            </main>

        </div>
    </div>
{% endblock main %}

{% block aside-right %}
    <aside class="span8">
        <div class="widget widget_recent_posts">
            <h3 class="widget_title">文章目录</h3>
            {{ post.toc|safe }}
        </div>
    </aside>
{% endblock %}

blog/templates/test.html
<html5>
    <head>
        <style>
            .container {
                display: flex;
                flex-direction: column;
                flex-wrap: wrap;
                align-content: center;
                height: 650px;
                background: #ccc;
            }

            .small, .medium, .large {
                margin: 0 5px 5px 0;
                background: #aaa;
            }

            .small {
                flex: 0 0 100px;
                width: 200px;
            }

            .medium {
                flex: 0 0 200px;
                width: 200px;
            }

            .large {
                flex: 0 0 300px;
                width: 200px;
            }
        </style>
    </head>
</html5>
<body>
<div class="container">
    <div class="left"></div>
    <div class="midden"></div>
    <div class="right"></div>
    <div class="small"></div>
    <div class="large"></div>
    <div class="medium"></div>
    <div class="medium"></div>
    <div class="medium"></div>
    <div class="small"></div>
    <div class="small"></div>
    <div class="large"></div>
    <div class="large"></div>

</div>
</body>